@extends('layouts.admin', ['title' => 'Event resources', 'heading' => 'Event resources & checklists', 'subheading' => 'Reusable handbook files, role guides and pre-start checklist templates.'])
@section('content')
<div class="grid two-col">
<section class="card card-pad"><h2>Add handbook or role resource</h2><form method="POST" action="{{ route('admin.operations.resources.store') }}" enctype="multipart/form-data" class="grid">@csrf
<div class="grid two-col"><label>Section number<input type="number" name="section_number" min="1" max="99"></label><label>Title<input name="title" required></label><label>Type<select name="resource_type"><option value="handbook">Handbook section</option><option value="cheat_sheet">Role cheat sheet</option><option value="help">Help & support</option></select></label><label>Applies to<select name="event_type"><option value="">All events</option><option value="competition">Competitions</option><option value="concert">Concerts</option></select></label><label>Role code<input name="role_code" placeholder="e.g. videographer"></label><label>Order<input type="number" name="sort_order" value="0" min="0"></label></div>
<label>Short description<textarea name="summary"></textarea></label><label>Help text (optional)<textarea name="content"></textarea></label><label>PDF or image<input type="file" name="file" accept="application/pdf,image/jpeg,image/png,image/webp"></label><label>External link (optional)<input type="url" name="external_url"></label><label style="display:flex;flex-direction:row;gap:8px"><input type="checkbox" name="is_active" value="1" checked style="width:auto"> Visible to crew</label><button>Add resource</button></form></section>
<section class="card card-pad"><h2>Add checklist template</h2><p class="muted">Use one checklist item per line. Leave role blank for every crew member.</p><form method="POST" action="{{ route('admin.operations.checklists.store') }}" class="grid">@csrf<label>Name<input name="name" required placeholder="Competition videographer pre-start"></label><div class="grid two-col"><label>Event type<select name="event_type"><option value="">All events</option><option value="competition">Competition</option><option value="concert">Concert</option></select></label><label>Role code<input name="role_code" placeholder="competition-videographer"></label></div><label>Checklist items<textarea name="items" required style="min-height:300px" placeholder="Check camera framing&#10;Check focus&#10;Record a test clip"></textarea></label><label style="display:flex;flex-direction:row;gap:8px"><input type="checkbox" name="is_active" value="1" checked style="width:auto"> Active</label><button>Add checklist</button></form></section>
</div>

<section class="card card-pad" style="margin-top:20px"><h2>Resource library</h2><div class="grid">@forelse($resources as $resource)<form method="POST" action="{{ route('admin.operations.resources.update',$resource) }}" enctype="multipart/form-data" class="card card-pad grid">@csrf @method('PUT')<div class="grid" style="grid-template-columns:80px 1.5fr 1fr 1fr 1fr"><label>Section<input type="number" name="section_number" value="{{ $resource->section_number }}"></label><label>Title<input name="title" value="{{ $resource->title }}" required></label><label>Type<select name="resource_type">@foreach(['handbook'=>'Handbook','cheat_sheet'=>'Cheat sheet','help'=>'Help'] as $value=>$label)<option value="{{ $value }}" @selected($resource->resource_type===$value)>{{ $label }}</option>@endforeach</select></label><label>Event<select name="event_type"><option value="">All</option><option value="competition" @selected($resource->event_type==='competition')>Competition</option><option value="concert" @selected($resource->event_type==='concert')>Concert</option></select></label><label>Role<input name="role_code" value="{{ $resource->role_code }}"></label></div><label>Summary<input name="summary" value="{{ $resource->summary }}"></label><label>Help text<textarea name="content">{{ $resource->content }}</textarea></label><div class="filters"><label>Replacement file<input type="file" name="file"></label><label>External URL<input type="url" name="external_url" value="{{ $resource->external_url }}"></label><input type="hidden" name="sort_order" value="{{ $resource->sort_order }}"><label style="display:flex;flex-direction:row"><input type="checkbox" name="is_active" value="1" @checked($resource->is_active) style="width:auto"> Active</label>@if($resource->fileUrl())<a href="{{ $resource->fileUrl() }}" target="_blank">View file ↗</a>@endif<button>Save</button></div></form>@empty<p class="muted">No resources yet.</p>@endforelse</div></section>

<section class="card card-pad" style="margin-top:20px"><h2>Checklist templates</h2><div class="grid two-col">@forelse($templates as $template)<form method="POST" action="{{ route('admin.operations.checklists.update',$template) }}" class="card card-pad grid">@csrf @method('PUT')<label>Name<input name="name" value="{{ $template->name }}" required></label><div class="grid two-col"><label>Event<select name="event_type"><option value="">All</option><option value="competition" @selected($template->event_type==='competition')>Competition</option><option value="concert" @selected($template->event_type==='concert')>Concert</option></select></label><label>Role<input name="role_code" value="{{ $template->role_code }}"></label></div><label>Items<textarea name="items" style="min-height:260px">{{ $template->items->pluck('instruction')->join("\n") }}</textarea></label><label style="display:flex;flex-direction:row"><input type="checkbox" name="is_active" value="1" @checked($template->is_active) style="width:auto"> Active</label><button>Save template</button></form>@empty<p class="muted">No checklists yet.</p>@endforelse</div></section>
@endsection
