@extends('layouts.admin', ['title' => 'Crew resources', 'heading' => 'Resources', 'subheading' => 'Reusable handbook files, role guides and crew support information.'])

@section('content')
@include('admin.crew-management._tabs')
<section class="card card-pad"><h2>Add handbook or role resource</h2><form method="POST" action="{{ route('admin.operations.resources.store') }}" enctype="multipart/form-data" class="grid">@csrf
<div class="grid two-col"><label>Section number<input type="number" name="section_number" min="1" max="99"></label><label>Title<input name="title" required></label><label>Type<select name="resource_type"><option value="handbook">Handbook section</option><option value="cheat_sheet">Role cheat sheet</option><option value="help">Help & support</option></select></label><label>Applies to<select name="event_type_definition_id"><option value="">All events</option>@foreach($eventTypes as $eventType)<option value="{{ $eventType->id }}">{{ $eventType->name }}</option>@endforeach</select></label><label>Role code<input name="role_code" placeholder="e.g. videographer"></label><label>Order<input type="number" name="sort_order" value="0" min="0"></label></div>
<label>Short description<textarea name="summary"></textarea></label><label>Help text (optional)<textarea name="content"></textarea></label><label>PDF or image<input type="file" name="file" accept="application/pdf,image/jpeg,image/png,image/webp"></label><label>External link (optional)<input type="url" name="external_url"></label><label style="display:flex;flex-direction:row;gap:8px"><input type="checkbox" name="is_active" value="1" checked style="width:auto"> Visible to crew</label><button>Add resource</button></form></section>

<section class="card card-pad" style="margin-top:20px"><h2>Resource library</h2><div class="grid">@forelse($resources as $resource)<form method="POST" action="{{ route('admin.operations.resources.update',$resource) }}" enctype="multipart/form-data" class="card card-pad grid">@csrf @method('PUT')<div class="grid" style="grid-template-columns:80px 1.5fr 1fr 1fr 1fr"><label>Section<input type="number" name="section_number" value="{{ $resource->section_number }}"></label><label>Title<input name="title" value="{{ $resource->title }}" required></label><label>Type<select name="resource_type">@foreach(['handbook'=>'Handbook','cheat_sheet'=>'Cheat sheet','help'=>'Help'] as $value=>$label)<option value="{{ $value }}" @selected($resource->resource_type===$value)>{{ $label }}</option>@endforeach</select></label><label>Event<select name="event_type_definition_id"><option value="">All</option>@foreach($eventTypes as $eventType)<option value="{{ $eventType->id }}" @selected($resource->event_type_definition_id===$eventType->id)>{{ $eventType->name }}</option>@endforeach</select></label><label>Role<input name="role_code" value="{{ $resource->role_code }}"></label></div><label>Summary<input name="summary" value="{{ $resource->summary }}"></label><label>Help text<textarea name="content">{{ $resource->content }}</textarea></label><div class="filters"><label>Replacement file<input type="file" name="file"></label><label>External URL<input type="url" name="external_url" value="{{ $resource->external_url }}"></label><input type="hidden" name="sort_order" value="{{ $resource->sort_order }}"><label style="display:flex;flex-direction:row"><input type="checkbox" name="is_active" value="1" @checked($resource->is_active) style="width:auto"> Active</label>@if($resource->fileUrl())<a href="{{ $resource->fileUrl() }}" target="_blank">View file ↗</a>@endif<button>Save</button></div></form>@empty<p class="muted">No resources yet.</p>@endforelse</div></section>
@endsection
