@php
    $event = $event ?? null;
    $selectedRoles = old('roles', $event?->roleRequirements?->map(fn($requirement) => $requirement->crewRole->code)->all() ?? []);
    $dayRows = old('days');
    if ($dayRows === null) {
        $dayRows = $event?->shifts?->groupBy(fn($shift) => $shift->shift_date?->toDateString())->map(function ($shifts, $date) {
            $morning = $shifts->first(fn($shift) => $shift->period->value === 'morning');
            $afternoon = $shifts->first(fn($shift) => $shift->period->value === 'afternoon');
            return [
                'date' => $date,
                'morning' => (bool) $morning,
                'afternoon' => (bool) $afternoon,
                'morning_uuid' => $morning?->uuid,
                'afternoon_uuid' => $afternoon?->uuid,
                'setup_period' => $morning?->requires_setup ? 'morning' : ($afternoon?->requires_setup ? 'afternoon' : ''),
                'set_down_period' => $morning?->requires_set_down ? 'morning' : ($afternoon?->requires_set_down ? 'afternoon' : ''),
            ];
        })->values()->all() ?? [[]];
    }
@endphp
<input type="hidden" name="event_type" value="competition">
<input type="hidden" name="event_type_definition_id" value="{{ old('event_type_definition_id', $event->event_type_definition_id ?? $selectedEventType->id ?? '') }}">
<div class="grid two-col"><div class="grid"><label>Saved competition<select id="competition-contact" name="competition_contact_id"><option value="">New or one-off competition</option>@foreach($competitionContacts as $contact)<option value="{{ $contact->id }}" data-name="{{ $contact->name }}" data-organiser="{{ $contact->organiser_name }}" data-email="{{ $contact->organiser_email }}" data-phone="{{ $contact->organiser_phone }}" @selected((string) old('competition_contact_id', $event?->competition_contact_id) === (string) $contact->id)>{{ $contact->name }}</option>@endforeach</select><span class="muted">Selecting a saved competition fills the contact details below.</span></label><label>Competition name<input id="competition-name" name="name" value="{{ old('name', $event?->name) }}" required></label><label>Organiser name<input id="organiser-name" name="organiser_name" value="{{ old('organiser_name', $event?->organiser_name) }}" required></label><label>Organiser email<input id="organiser-email" type="email" name="organiser_email" value="{{ old('organiser_email', $event?->organiser_email) }}" required></label><label>Organiser phone<input id="organiser-phone" type="tel" name="organiser_phone" value="{{ old('organiser_phone', $event?->organiser_phone) }}" required></label><label>Venue<select name="venue_id"><option value="">Not set</option>@foreach($venues as $venue)<option value="{{ $venue->id }}" @selected((string) old('venue_id', $event?->venue_id) === (string) $venue->id)>{{ $venue->name }}</option>@endforeach</select></label>@if($event?->logo_path)<img class="entity-logo" src="{{ $event->logoUrl() }}" alt="{{ $event->name }} logo">@endif<label>Competition logo<input type="file" name="logo" accept="image/jpeg,image/png,image/webp"><span class="muted">JPG, PNG or WebP. The full logo will be shown without cropping.</span></label></div><label>Administrator notes<textarea name="admin_notes" style="min-height:120px;font-family:inherit">{{ old('admin_notes', $event?->admin_notes) }}</textarea></label></div>

<div class="card card-pad" style="margin-top:20px"><h2>Roles for this competition</h2><p class="muted">These roles apply to every shift. Individual overrides can be added later if an unusual shift needs them.</p><div class="filters" style="margin-top:14px">@foreach(['competition-videographer'=>'Videographer V','competition-photographer-p1'=>'Photographer P1','competition-photographer-p2'=>'Photographer P2'] as $code=>$label)<label style="display:flex;grid-template-columns:auto 1fr;align-items:center;border:1px solid var(--line);padding:12px"><input type="checkbox" name="roles[]" value="{{ $code }}" style="width:auto" @checked(in_array($code,$selectedRoles))> <strong>{{ $label }}</strong></label>@endforeach</div></div>

<div class="card card-pad" style="margin-top:20px"><div class="toolbar"><div><h2>Competition days</h2><div class="muted">Choose a date and tick morning, afternoon, or both. Times can be added later.</div></div><button type="button" id="add-day">Add competition day</button></div><div id="day-rows">@foreach($dayRows as $index=>$day)<div class="card card-pad day-row" style="margin-top:14px"><div class="toolbar"><strong>Day <span class="day-number">{{ $index+1 }}</span></strong><button type="button" class="button danger remove-day">Remove</button></div><input type="hidden" name="days[{{ $index }}][morning_uuid]" value="{{ data_get($day,'morning_uuid') }}"><input type="hidden" name="days[{{ $index }}][afternoon_uuid]" value="{{ data_get($day,'afternoon_uuid') }}"><div class="grid" style="grid-template-columns:1.3fr 1fr 1fr 1.2fr 1.2fr"><label>Date<input type="date" name="days[{{ $index }}][date]" value="{{ data_get($day,'date') }}" required></label><label style="display:flex;grid-template-columns:auto 1fr;align-items:center"><input type="hidden" name="days[{{ $index }}][morning]" value="0"><input type="checkbox" name="days[{{ $index }}][morning]" value="1" style="width:auto" @checked(data_get($day,'morning'))> Morning</label><label style="display:flex;grid-template-columns:auto 1fr;align-items:center"><input type="hidden" name="days[{{ $index }}][afternoon]" value="0"><input type="checkbox" name="days[{{ $index }}][afternoon]" value="1" style="width:auto" @checked(data_get($day,'afternoon'))> Afternoon</label><label>Setup<select name="days[{{ $index }}][setup_period]"><option value="">None</option><option value="morning" @selected(data_get($day,'setup_period')==='morning')>Morning</option><option value="afternoon" @selected(data_get($day,'setup_period')==='afternoon')>Afternoon</option></select></label><label>Set-down<select name="days[{{ $index }}][set_down_period]"><option value="">None</option><option value="morning" @selected(data_get($day,'set_down_period')==='morning')>Morning</option><option value="afternoon" @selected(data_get($day,'set_down_period')==='afternoon')>Afternoon</option></select></label></div></div>@endforeach</div></div>
<template id="day-template"><div class="card card-pad day-row" style="margin-top:14px"><div class="toolbar"><strong>Day <span class="day-number"></span></strong><button type="button" class="button danger remove-day">Remove</button></div><input type="hidden" name="days[__INDEX__][morning_uuid]" value=""><input type="hidden" name="days[__INDEX__][afternoon_uuid]" value=""><div class="grid" style="grid-template-columns:1.3fr 1fr 1fr 1.2fr 1.2fr"><label>Date<input type="date" name="days[__INDEX__][date]" required></label><label style="display:flex;grid-template-columns:auto 1fr;align-items:center"><input type="hidden" name="days[__INDEX__][morning]" value="0"><input type="checkbox" name="days[__INDEX__][morning]" value="1" style="width:auto"> Morning</label><label style="display:flex;grid-template-columns:auto 1fr;align-items:center"><input type="hidden" name="days[__INDEX__][afternoon]" value="0"><input type="checkbox" name="days[__INDEX__][afternoon]" value="1" style="width:auto"> Afternoon</label><label>Setup<select name="days[__INDEX__][setup_period]"><option value="">None</option><option value="morning">Morning</option><option value="afternoon">Afternoon</option></select></label><label>Set-down<select name="days[__INDEX__][set_down_period]"><option value="">None</option><option value="morning">Morning</option><option value="afternoon">Afternoon</option></select></label></div></div></template>
<div style="margin-top:16px"><button>{{ $submitLabel }}</button> <a class="button secondary" href="{{ route('admin.scheduling-events.index') }}">Cancel</a></div>
@push('scripts')<script nonce="{{ request()->attributes->get('csp_nonce') }}">(()=>{const contact=document.getElementById('competition-contact');contact.addEventListener('change',()=>{const option=contact.selectedOptions[0];if(!option?.value)return;document.getElementById('competition-name').value=option.dataset.name;document.getElementById('organiser-name').value=option.dataset.organiser;document.getElementById('organiser-email').value=option.dataset.email;document.getElementById('organiser-phone').value=option.dataset.phone;});const rows=document.getElementById('day-rows');const template=document.getElementById('day-template');let next={{ count($dayRows) }};function number(){rows.querySelectorAll('.day-number').forEach((node,index)=>node.textContent=index+1)}document.getElementById('add-day').addEventListener('click',()=>{rows.insertAdjacentHTML('beforeend',template.innerHTML.replaceAll('__INDEX__',next++));number()});rows.addEventListener('click',event=>{if(event.target.classList.contains('remove-day')&&rows.querySelectorAll('.day-row').length>1){event.target.closest('.day-row').remove();number()}})})();</script>@endpush
