@extends('layouts.admin', ['title' => $event->name, 'heading' => $event->name, 'subheading' => ($event->venue?->name ?? 'Venue not set')])
@section('content')
@include('admin.event-management._tabs')
<div class="toolbar"><div><span class="badge">{{ $event->availability_status->value }}</span> @if($event->availability_deadline)<span class="muted">Replies due {{ $event->availability_deadline->format('j M Y, g:i a') }}</span>@endif</div>@if($event->event_type->value==='competition')<a class="button secondary" href="{{ route('admin.scheduling-events.edit',$event) }}">Edit days and roles</a>@endif</div>
@if($event->event_type->value==='competition')<div class="card card-pad" style="margin-bottom:20px"><h2>Competition contact</h2><div class="detail-list" style="margin-top:12px"><dt>Organiser</dt><dd>{{ $event->organiser_name }}</dd><dt>Email</dt><dd><a href="mailto:{{ $event->organiser_email }}">{{ $event->organiser_email }}</a></dd><dt>Phone</dt><dd><a href="tel:{{ $event->organiser_phone }}">{{ $event->organiser_phone }}</a></dd></div></div>@endif
@if($event->logo_path)<div class="card card-pad" style="margin-bottom:20px"><img class="entity-logo" src="{{ $event->logoUrl() }}" alt="{{ $event->name }} logo" style="width:min(360px,100%);margin:auto"></div>@endif
<div class="grid two-col" style="margin-bottom:20px"><div class="card card-pad"><h2>Crew event information</h2><form method="POST" action="{{ route('admin.scheduling-events.operations.update',$event) }}" enctype="multipart/form-data" class="grid">@csrf @method('PUT')<label>Crew job brief<textarea name="crew_brief" style="min-height:150px" placeholder="Arrival instructions, contacts, job priorities and event-specific information">{{ $event->crew_brief }}</textarea></label><label>Team Leader only notes<textarea name="team_leader_notes" style="min-height:100px">{{ $event->team_leader_notes }}</textarea></label><label>Programme / run sheet<input type="file" name="programme" accept="application/pdf,image/jpeg,image/png,image/webp"></label>@if($event->programmeUrl())<a href="{{ $event->programmeUrl() }}" target="_blank">View current programme ↗</a>@endif<button>Save event information</button></form></div><div class="card card-pad"><h2>Venue map</h2>@if($event->venue)@if($event->venue->mapUrl())<img src="{{ $event->venue->mapUrl() }}" alt="{{ $event->venue->name }} map" style="width:100%;max-height:280px;object-fit:contain;background:#111">@endif<form method="POST" action="{{ route('admin.venues.map.update',$event->venue) }}" enctype="multipart/form-data" class="grid" style="margin-top:12px">@csrf @method('PUT')<label>Upload reusable map for {{ $event->venue->name }}<input type="file" name="map" accept="image/jpeg,image/png,image/webp" required></label><button>Save venue map</button></form><p class="muted">This map automatically appears on every shift at this venue.</p>@else<p class="muted">Choose a venue before adding its reusable map.</p>@endif</div></div>
<section class="card card-pad" style="margin-top:20px"><div class="toolbar"><div><p class="eyebrow">Event communication</p><h2>Announcements & chat</h2></div><span class="muted">Visible to assigned crew</span></div><form method="POST" action="{{ route('admin.scheduling-events.messages.store',$event) }}" enctype="multipart/form-data" class="grid" style="margin-top:14px">@csrf<div class="filters"><label>Message type<select name="message_type"><option value="discussion">Normal message</option><option value="announcement">Important announcement — acknowledgement required</option></select></label><label>Optional attachment<input type="file" name="attachment" accept="image/jpeg,image/png,image/webp,application/pdf,.doc,.docx,.xls,.xlsx,.csv,.txt"></label></div><label>Message<textarea name="body" maxlength="10000" placeholder="Share an update, ask a question or explain the attachment"></textarea></label><button>Post to event</button></form><div style="margin-top:18px">@forelse($event->messages->sortBy('created_at') as $message)@php($readCount=$message->reads->whereIn('user_id',$assignedCrewUserIds)->pluck('user_id')->unique()->count())<article style="margin-top:10px;padding:12px;border:1px solid {{ $message->isAnnouncement()?'#f0c77b':'var(--line)' }};border-radius:5px;background:{{ $message->isAnnouncement()?'#fff8e8':'#fff' }}"><div class="toolbar"><strong>{{ $message->isAnnouncement()?'📣 Important announcement':'💬 Message' }} · {{ $message->author->name }}</strong><span class="muted">{{ $message->created_at->format('j M Y, g:i a') }}</span></div>@if($message->body)<p style="margin:8px 0 0">{!! nl2br(e($message->body)) !!}</p>@endif @if($message->attachmentUrl())<p style="margin:8px 0 0"><a href="{{ $message->attachmentUrl() }}" target="_blank" rel="noopener">📎 {{ $message->attachment_name }} ↗</a></p>@endif @if($message->isAnnouncement())<p class="muted" style="margin:8px 0 0">Acknowledged by {{ $readCount }} of {{ $assignedCrewUserIds->count() }} assigned crew.</p>@endif</article>@empty<p class="muted" style="margin-top:14px">No event messages yet.</p>@endforelse</div></section>
<div class="card card-pad"><h2>Roles for every shift</h2><div class="filters" style="margin-top:12px">@forelse($event->roleRequirements as $requirement)<span class="badge">{{ $requirement->crewRole->name }}</span>@empty<span class="muted">No roles selected.</span>@endforelse</div></div>
<div class="card card-pad" style="margin-top:20px"><h2>Schedule</h2><p class="muted">Times may remain TBC while a competition is in draft or collecting availability.</p><div class="grid" style="margin-top:14px">@foreach($event->shifts->sortBy(fn($shift)=>$shift->shift_date->toDateString().($shift->period?->value ?? 'concert')) as $shift)<div class="card card-pad"><div class="toolbar"><div><strong>{{ $shift->shift_date->format('D j M Y') }}@if($shift->period) · {{ ucfirst($shift->period->value) }}@endif</strong><div class="muted">@if($shift->requires_setup) Setup · @endif @if($shift->requires_set_down) Set-down @endif</div></div>@if($shift->starts_at)<div><strong>{{ $shift->starts_at->format('g:i a') }}–{{ $shift->estimated_finish_at->format('g:i a') }}</strong><div class="muted">Posted arrival {{ $shift->posted_arrival_at->format('g:i a') }}</div></div>@else<span class="badge expired">Times TBC</span>@endif</div><form method="POST" action="{{ route('admin.scheduling-events.shifts.times',[$event,$shift]) }}" class="filters">@csrf @method('PATCH')<label>Start time<input type="time" name="start_time" value="{{ $shift->starts_at?->format('H:i') }}" required></label><label>Finish before set-down<input type="time" name="finish_time" value="{{ $shift->estimated_finish_at?->copy()->subMinutes($shift->requires_set_down?20:0)->format('H:i') }}" required></label><button>Save times</button></form>@if($shift->assignments->isNotEmpty())<div style="margin-top:12px;border-top:1px solid var(--line);padding-top:10px"><strong>Pre-start progress</strong>@foreach($shift->assignments as $assignment)@php($progress=$checklistProgress[$assignment->id]??['done'=>0,'total'=>0])<div class="toolbar" style="margin-top:5px"><span>{{ $assignment->crewProfile->preferred_name }} · {{ $assignment->role->name }}</span><span class="badge {{ $progress['total']>0&&$progress['done']===$progress['total']?'':'pending' }}">{{ $progress['done'] }} / {{ $progress['total'] }} complete</span></div>@endforeach</div>@endif</div>@endforeach</div></div>
<section class="card card-pad" style="margin-top:20px"><div class="toolbar"><div><p class="eyebrow">Timekeeping</p><h2>Crew time records</h2></div><span class="muted">Flags ask for a check; they do not reject or alter a time.</span></div><div style="overflow:auto;margin-top:12px"><table><thead><tr><th>Shift / crew</th><th>Clock-in</th><th>Payable start</th><th>Finish</th><th>Status</th><th>Correction</th></tr></thead><tbody>@forelse($event->shifts->flatMap->assignments as $timeAssignment)@php($entry=$timeAssignment->timeEntry)@php($flags=$entry?->reviewFlags()??[])<tr><td><strong>{{ $timeAssignment->crewProfile->preferred_name }}</strong><div class="muted">{{ $timeAssignment->shift->shift_date->format('D j M') }} · {{ $timeAssignment->role->name }}</div></td><td>{{ $entry?->actual_clock_in_at?->format('g:i a') ?? 'Not started' }}</td><td>{{ $entry?->payable_start_at?->format('g:i a') ?? '—' }}</td><td>{{ $entry?->actual_finish_at?->format('g:i a') ?? 'Not finished' }}</td><td>@if($flags)@foreach($flags as $flag)<div style="color:var(--warn);font-size:12px">Check recommended: {{ $flag }}</div>@endforeach @elseif($entry)<span class="badge" style="background:#dcfce7;color:var(--ok)">Recorded</span>@else<span class="muted">No entry</span>@endif</td><td><details><summary>Edit</summary><form method="POST" action="{{ route('admin.scheduling-assignments.time.update',$timeAssignment) }}" class="grid" style="min-width:250px;margin-top:8px">@csrf @method('PUT')<label>Actual clock-in<input type="datetime-local" name="actual_clock_in_at" value="{{ $entry?->actual_clock_in_at?->format('Y-m-d\TH:i') }}"></label><label>Actual finish<input type="datetime-local" name="actual_finish_at" value="{{ $entry?->actual_finish_at?->format('Y-m-d\TH:i') }}"></label><label>Optional note<input name="optional_note" value="{{ $entry?->optional_note }}"></label><button>Save</button></form></details></td></tr>@empty<tr><td colspan="6" class="muted">No crew assignments yet.</td></tr>@endforelse</tbody></table></div></section>
<section class="card card-pad" style="margin-top:20px">
    <div class="toolbar">
        <div><p class="eyebrow">Payments</p><h2>Payment preview</h2></div>
        <a class="button secondary" href="{{ route('admin.payments.index') }}">Manage rates</a>
    </div>
    <p class="muted">Calculated from the rate that applies on the shift date. This is a preview only and does not approve or pay anything.</p>
    <div style="overflow:auto;margin-top:12px">
        <table>
            <thead><tr><th>Shift / crew</th><th>Rate</th><th>Base</th><th>Allowances</th><th>Total preview</th><th>Review</th></tr></thead>
            <tbody>
            @forelse($event->shifts->flatMap->assignments as $paymentAssignment)
                @php($preview=$paymentPreviews[$paymentAssignment->id])
                <tr>
                    <td><strong>{{ $paymentAssignment->crewProfile->preferred_name }}</strong><div class="muted">{{ $paymentAssignment->shift->shift_date->format('D j M') }} · {{ $paymentAssignment->role->name }}@if($paymentAssignment->is_team_leader) · Team Leader @endif</div></td>
                    <td>@if($preview['rate']){{ $preview['rate']->name }}<div class="muted">${{ number_format((float)$preview['rate']->amount,2) }}{{ $preview['rate']->calculation_type==='hourly'?'/hr':'' }}</div>@else<span class="badge expired">Not configured</span>@endif</td>
                    <td>@if($preview['base']!==null)<strong>${{ number_format($preview['base'],2) }}</strong>@if($preview['hours']!==null)<div class="muted">{{ number_format($preview['hours'],2) }} hours</div>@endif @else—@endif</td>
                    <td>
                        @if($preview['allowanceLines']->isNotEmpty())
                            @foreach($preview['allowanceLines'] as $line)<div>{{ $line['rate']?->name ?? str($line['key'])->replace('_',' ')->title() }}: {{ $line['amount']!==null?'$'.number_format($line['amount'],2):'rate missing' }}</div>@endforeach
                        @else<span class="muted">None</span>@endif
                        <details style="margin-top:6px"><summary>Edit</summary><form method="POST" action="{{ route('admin.scheduling-assignments.allowances.update',$paymentAssignment) }}" class="grid" style="min-width:250px;margin-top:8px">@csrf @method('PUT')@foreach(\App\Features\Scheduling\Support\PaymentRateCatalog::allowancesForEvent($event->event_type->value) as $allowanceKey => [$allowanceName])<label style="display:flex;flex-direction:row;align-items:center;gap:8px"><input type="checkbox" name="allowances[]" value="{{ $allowanceKey }}" style="width:auto" @checked($paymentAssignment->allowances->contains('allowance_key',$allowanceKey))> {{ $allowanceName }}</label>@endforeach @if($event->event_type->value==='concert')<span class="muted">Equipment pickup/drop-off is included in the flat rate.</span>@endif<button>Save allowances</button></form></details>
                    </td>
                    <td>@if($preview['total']!==null)<strong>${{ number_format($preview['total'],2) }}</strong><div class="muted">Superable component: ${{ number_format($preview['superable'],2) }}</div>@else—@endif</td>
                    <td>@forelse($preview['flags'] as $flag)<div style="color:var(--warn);font-size:12px">Check recommended: {{ $flag }}</div>@empty<span class="badge" style="background:#dcfce7;color:var(--ok)">Ready to review</span>@endforelse</td>
                </tr>
            @empty
                <tr><td colspan="6" class="muted">No crew assignments yet.</td></tr>
            @endforelse
            </tbody>
        </table>
    </div>
</section>
<div class="card card-pad" style="margin-top:20px"><h2>Availability</h2>@if($event->availability_status->value==='draft')<p class="muted">Opening availability makes these shifts visible to active crew. Exact competition times may still be TBC.</p><form method="POST" action="{{ route('admin.scheduling-events.availability',$event) }}" class="filters">@csrf @method('PATCH')<input type="hidden" name="availability_status" value="open"><label>Response deadline date <span class="muted">(5:00 pm)</span><input type="date" name="availability_deadline" required></label><button>Open availability</button></form>@elseif($event->availability_status->value==='open')<form method="POST" action="{{ route('admin.scheduling-events.availability',$event) }}">@csrf @method('PATCH')<input type="hidden" name="availability_status" value="closed"><button class="danger">Close availability</button></form>@else<p class="muted">Availability is closed.</p>@endif</div>
<div class="grid two-col" style="margin-top:20px">@foreach($event->shifts as $shift)@php($responses=$shift->availabilityResponses)<div class="card card-pad"><h2>{{ $shift->shift_date->format('j M') }}@if($shift->period) · {{ ucfirst($shift->period->value) }}@endif</h2><p class="muted">{{ $responses->count() }} of {{ $activeCrewCount }} crew replied · {{ max(0,$activeCrewCount-$responses->count()) }} not yet replied</p><table><thead><tr><th>Crew</th><th>Response</th><th>Note</th></tr></thead><tbody>@forelse($responses as $response)<tr><td>{{ $response->crewProfile->preferred_name }}</td><td><span class="badge">{{ $response->status->value }}</span></td><td>{{ $response->note?:'—' }}</td></tr>@empty<tr><td colspan="3" class="muted">No replies yet.</td></tr>@endforelse</tbody></table></div>@endforeach</div>
@endsection
