@php
    $contact = $contact ?? null;
    $staffRows = old('staff', $contact?->staff?->map(fn ($person) => [
        'name' => $person->name, 'role' => $person->role,
        'emails' => $person->emailString(), 'phone' => $person->phone,
    ])->all() ?? []);
    $staffRows = count($staffRows) ? $staffRows : [['name' => '', 'role' => '', 'emails' => '', 'phone' => '']];
@endphp
<input type="hidden" name="is_active" value="{{ old('is_active', ($contact?->is_active ?? true) ? '1' : '0') }}">
<div class="grid two-col"><div class="grid"><label>Competition name<input name="name" value="{{ old('name', $contact?->name) }}" required></label><label>Code<input name="code" value="{{ old('code', $contact?->code) }}" maxlength="50" placeholder="e.g. PDC"><span class="muted">Shown beneath the competition name.</span></label>@if($contact?->logo_path)<img class="entity-logo" src="{{ $contact->logoUrl() }}" alt="{{ $contact->name }} logo">@endif<label>Competition logo<input type="file" name="logo" accept="image/jpeg,image/png,image/webp"><span class="muted">JPG, PNG or WebP. The full logo will be shown without cropping.</span></label></div><div class="grid"><label>Internal notes<textarea name="notes" style="min-height:120px">{{ old('notes', $contact?->notes) }}</textarea></label></div></div>

<section style="margin-top:24px"><div class="toolbar"><div><h2>Competition staff</h2><div class="muted">The first person is used to prefill new events. Separate multiple email addresses with commas.</div></div><button class="secondary" id="add-competition-staff" type="button">Add staff member</button></div><div class="grid" id="competition-staff-rows">
@foreach($staffRows as $index => $person)<div class="card card-pad competition-staff-row" style="background:var(--surface-subtle, #f8fafc)"><div class="toolbar"><strong class="competition-staff-number">Staff member {{ $loop->iteration }}</strong><button class="button secondary remove-competition-staff" type="button">Remove</button></div><div class="grid two-col"><label>Name<input name="staff[{{ $index }}][name]" value="{{ $person['name'] ?? '' }}" maxlength="255" required></label><label>Role / position<input name="staff[{{ $index }}][role]" value="{{ $person['role'] ?? '' }}" maxlength="255" placeholder="e.g. Competition director"></label><label>Email addresses<input name="staff[{{ $index }}][emails]" value="{{ $person['emails'] ?? '' }}" maxlength="2000" placeholder="name@example.com, accounts@example.com" required><span class="muted">Use a comma between addresses.</span></label><label>Phone<input name="staff[{{ $index }}][phone]" value="{{ $person['phone'] ?? '' }}" maxlength="50"></label></div></div>@endforeach
</div></section>

<template id="competition-staff-template"><div class="card card-pad competition-staff-row" style="background:var(--surface-subtle, #f8fafc)"><div class="toolbar"><strong class="competition-staff-number">Staff member</strong><button class="button secondary remove-competition-staff" type="button">Remove</button></div><div class="grid two-col"><label>Name<input name="staff[__INDEX__][name]" maxlength="255" required></label><label>Role / position<input name="staff[__INDEX__][role]" maxlength="255" placeholder="e.g. Competition director"></label><label>Email addresses<input name="staff[__INDEX__][emails]" maxlength="2000" placeholder="name@example.com, accounts@example.com" required><span class="muted">Use a comma between addresses.</span></label><label>Phone<input name="staff[__INDEX__][phone]" maxlength="50"></label></div></div></template>

@push('scripts')<script nonce="{{ request()->attributes->get('csp_nonce') }}">(()=>{const rows=document.getElementById('competition-staff-rows');const template=document.getElementById('competition-staff-template');let next={{ count($staffRows) }};const renumber=()=>rows.querySelectorAll('.competition-staff-number').forEach((node,index)=>node.textContent=`Staff member ${index+1}`);document.getElementById('add-competition-staff').addEventListener('click',()=>{rows.insertAdjacentHTML('beforeend',template.innerHTML.replaceAll('__INDEX__',next++));renumber()});rows.addEventListener('click',event=>{if(!event.target.classList.contains('remove-competition-staff'))return;event.target.closest('.competition-staff-row').remove();if(!rows.querySelector('.competition-staff-row'))document.getElementById('add-competition-staff').click();renumber()})})();</script>@endpush
<div style="margin-top:16px"><button>{{ $submitLabel }}</button> <a class="button secondary" href="{{ route('admin.competition-contacts.index') }}">Cancel</a></div>
