@extends('layouts.crew', ['title' => $event->name.' shift details'])
@section('content')
@php
    $shift=$assignment->shift; $venue=$event->venue;
    $completedIds=$assignment->checklistCompletions->whereNotNull('completed_at')->pluck('checklist_template_item_id');
    $allItems=$templates->flatMap->items; $done=$completedIds->intersect($allItems->pluck('id'))->count(); $total=$allItems->count();
@endphp
<div class="page-heading"><div><p class="eyebrow">{{ $event->event_type->value }} shift</p><h1>{{ $event->name }}</h1><p class="muted">{{ $assignment->role->name }} · {{ $shift->shift_date?->format('D j M Y') }}</p></div><a class="button secondary" href="{{ route('crew.availability.index',['view'=>'upcoming']) }}">Back to shifts</a></div>

<section class="card profile-section"><h2>Shift details</h2><div class="detail-grid"><div><span class="detail-label">Arrival</span><strong>{{ $shift->posted_arrival_at?->format('g:i a') ?? 'TBC' }}</strong></div><div><span class="detail-label">Event time</span><strong>{{ $shift->starts_at?->format('g:i a') ?? 'TBC' }}–{{ $shift->estimated_finish_at?->format('g:i a') ?? 'TBC' }}</strong></div><div><span class="detail-label">Venue</span><strong>{{ $venue?->name ?? 'TBC' }}</strong></div></div>@if($event->crew_brief)<div class="venue-details"><strong>Job brief</strong><p>{!! nl2br(e($event->crew_brief)) !!}</p></div>@endif @if($assignment->is_team_leader && $event->team_leader_notes)<div class="profile-warning"><strong>Team Leader information</strong><p>{!! nl2br(e($event->team_leader_notes)) !!}</p></div>@endif</section>

@if(!$assignment->timeEntry?->actual_clock_in_at && !$shift->shift_date->lt(today()))<section class="card profile-section"><p class="eyebrow">Can’t work this shift?</p><h2>Organise cover</h2>@if($assignment->coverRequests->where('status','open')->isNotEmpty())<p>A cover request is currently open.</p><a class="button secondary" href="{{ route('crew.availability.index',['view'=>'cover']) }}">View cover requests</a>@else<p class="muted">Ask one person, several people or all eligible crew. You can include an optional personal message.</p><a class="button secondary" href="{{ route('crew.cover.create',$assignment) }}">Organise cover</a>@endif</section>@endif

@php($timeEntry=$assignment->timeEntry)


@if($venue)<section class="card profile-section"><h2>Venue, parking & access</h2>@if($venue->mapUrl())<a href="{{ $venue->mapUrl() }}" target="_blank" rel="noopener"><img src="{{ $venue->mapUrl() }}" alt="Map for {{ $venue->name }}" style="width:100%;max-height:520px;object-fit:contain;border-radius:6px;background:#111"></a>@endif @if($venue->referenceImageUrl())<p><a href="{{ $venue->referenceImageUrl() }}" target="_blank" rel="noopener">View venue reference image ↗</a></p>@endif @if($venue->parking_notes)<p><strong>Parking:</strong> {{ $venue->parking_notes }}</p>@endif @if($venue->access_notes)<p><strong>Access:</strong> {{ $venue->access_notes }}</p>@endif @if($venue->operational_notes)<p><strong>Operational notes:</strong> {{ $venue->operational_notes }}</p>@endif</section>@endif

@if($event->programmeUrl())<section class="card profile-section"><h2>Programme / run sheet</h2><a class="button" href="{{ $event->programmeUrl() }}" target="_blank" rel="noopener">Open programme ↗</a></section>@endif

<section class="card profile-section"><div class="section-heading"><div><p class="eyebrow">Event communication</p><h2>Announcements & chat</h2></div><a class="button secondary" href="{{ route('crew.chat.event',$event) }}">Open messages in My Chat</a></div><div class="event-messages">@forelse($event->messages->sortBy('created_at') as $message)@php($acknowledged=$message->reads->contains('user_id',auth()->id()))<article class="event-message {{ $message->isAnnouncement()?'announcement':'' }}"><div class="message-heading"><strong>{{ $message->isAnnouncement()?'📣 Important announcement':'💬 '.$message->author->name }}</strong><span>{{ $message->created_at->format('j M, g:i a') }}</span></div>@if($message->body)<p>{!! nl2br(e($message->body)) !!}</p>@endif @if($message->attachmentUrl())<a href="{{ $message->attachmentUrl() }}" target="_blank" rel="noopener">📎 {{ $message->attachment_name }} ↗</a>@endif @if($message->isAnnouncement())@if($acknowledged)<div class="announcement-read">✅ You acknowledged this</div>@else<form method="POST" action="{{ route('crew.assignments.messages.acknowledge',[$assignment,$message]) }}">@csrf<button type="submit">Acknowledge announcement</button></form>@endif @endif</article>@empty<p class="muted">No messages for this event yet.</p>@endforelse</div><form method="POST" action="{{ route('crew.assignments.messages.store',$assignment) }}" enctype="multipart/form-data" class="message-form">@csrf<input type="hidden" name="message_type" value="discussion"><label>Message<textarea name="body" maxlength="10000" placeholder="Ask a question, report a problem or share an update"></textarea></label><label>Optional image or document<input type="file" name="attachment" accept="image/jpeg,image/png,image/webp,application/pdf,.doc,.docx,.xls,.xlsx,.csv,.txt"></label><button type="submit">Post message</button></form></section>

<section class="card profile-section"><div class="section-heading"><div><p class="eyebrow">Pre-start</p><h2>Your checklist</h2></div><span class="count-pill" id="checklist-progress">{{ $done }} of {{ $total }}</span></div>@forelse($templates as $template)<div class="checklist-group"><h3>{{ $template->name }}</h3>@foreach($template->items as $item)@php($checked=$completedIds->contains($item->id))<label class="checklist-item {{ $checked?'complete':'' }}"><input type="checkbox" data-checklist-url="{{ route('crew.assignments.checklist.toggle',[$assignment,$item]) }}" @checked($checked)><span>{{ $item->instruction }}</span></label>@endforeach</div>@empty<p class="muted">No checklist has been assigned to this role yet.</p>@endforelse</section>

@if($resources->isNotEmpty())<section><div class="section-heading"><div><p class="eyebrow">Quick reference</p><h2>Guides for this shift</h2></div><a href="{{ route('crew.help.index') }}">Full handbook</a></div><div class="resource-grid">@foreach($resources as $resource)<article class="card resource-card"><span class="type-label">{{ str_replace('_',' ',$resource->resource_type) }}</span><h3>{{ $resource->title }}</h3><p class="muted">{{ $resource->summary }}</p><div class="resource-actions">@if($resource->fileUrl())<a class="button secondary" href="{{ $resource->fileUrl() }}" target="_blank">Open guide ↗</a>@endif @if($resource->external_url)<a href="{{ $resource->external_url }}" target="_blank">Open link ↗</a>@endif</div></article>@endforeach</div></section>@endif
@endsection
@push('scripts')<script nonce="{{ request()->attributes->get('csp_nonce') }}">document.querySelectorAll('[data-checklist-url]').forEach(box=>box.addEventListener('change',async()=>{const previous=!box.checked;box.disabled=true;try{const response=await fetch(box.dataset.checklistUrl,{method:'PUT',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body:JSON.stringify({completed:box.checked})});if(!response.ok)throw new Error();box.closest('.checklist-item').classList.toggle('complete',box.checked);const boxes=[...document.querySelectorAll('[data-checklist-url]')];document.getElementById('checklist-progress').textContent=`${boxes.filter(item=>item.checked).length} of ${boxes.length}`;}catch(error){box.checked=previous;alert('That checklist update could not be saved. Please try again.')}finally{box.disabled=false}}));</script>@endpush
