@extends('layouts.admin', [
    'title' => 'Download Link Detail',
    'heading' => 'Download Link Detail',
    'subheading' => $downloadLink->storage_key,
])

@section('content')
    <section class="grid two-col">
        <div class="card card-pad">
            <h2>Link Metadata</h2>
            <dl class="detail-list" style="margin-top: 16px;">
                <dt>UUID</dt>
                <dd>{{ $downloadLink->uuid }}</dd>
                <dt>Status</dt>
                <dd><span class="badge {{ $downloadLink->status }}">{{ $downloadLink->status }}</span></dd>
                <dt>Disk</dt>
                <dd>{{ $downloadLink->storage_disk }}</dd>
                <dt>Storage key</dt>
                <dd>{{ $downloadLink->storage_key }}</dd>
                <dt>Filename</dt>
                <dd>{{ $downloadLink->original_filename ?? 'Unknown' }}</dd>
                <dt>Purpose</dt>
                <dd>{{ $downloadLink->purpose ?? 'None' }}</dd>
                <dt>Generated by</dt>
                <dd>{{ $downloadLink->generatedBy?->name ?? 'Unknown' }}</dd>
                <dt>Created</dt>
                <dd>{{ $downloadLink->created_at?->toDayDateTimeString() }}</dd>
                <dt>Expires</dt>
                <dd>{{ $downloadLink->expires_at?->toDayDateTimeString() ?? 'Never' }}</dd>
                <dt>First opened</dt>
                <dd>{{ $downloadLink->first_opened_at?->toDayDateTimeString() ?? 'Not opened' }}</dd>
                <dt>Last opened</dt>
                <dd>{{ $downloadLink->last_opened_at?->toDayDateTimeString() ?? 'Not opened' }}</dd>
                <dt>Download count</dt>
                <dd>{{ number_format($downloadLink->download_count) }}</dd>
                <dt>Notes</dt>
                <dd>{{ $downloadLink->notes ?? 'None' }}</dd>
            </dl>
        </div>

        <div class="card card-pad">
            <h2>Security State</h2>
            <p class="muted">The original public token is not stored, so existing tracking URLs cannot be re-displayed after creation.</p>

            @if ($downloadLink->status !== 'revoked')
                <form method="POST" action="{{ route('admin.download-links.revoke', $downloadLink) }}" style="display:grid;gap:12px;margin-top:16px;">
                    @csrf
                    @method('PATCH')
                    <label>
                        Revoke reason
                        <textarea name="reason" style="min-height:110px;" placeholder="Optional internal reason"></textarea>
                    </label>
                    <button class="danger" type="submit">Revoke link</button>
                </form>
            @else
                <dl class="detail-list" style="margin-top: 16px;">
                    <dt>Revoked at</dt>
                    <dd>{{ $downloadLink->revoked_at?->toDayDateTimeString() }}</dd>
                    <dt>Revoked by</dt>
                    <dd>{{ $downloadLink->revokedBy?->name ?? 'Unknown' }}</dd>
                    <dt>Reason</dt>
                    <dd>{{ $downloadLink->revoke_reason ?? 'None' }}</dd>
                </dl>
            @endif
        </div>
    </section>

    <section class="card" style="margin-top: 18px;">
        <div class="card-pad">
            <h2>Access History</h2>
        </div>
        <table>
            <thead>
                <tr>
                    <th>When</th>
                    <th>Result</th>
                    <th>IP</th>
                    <th>User agent</th>
                    <th>Referrer</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($accesses as $access)
                    <tr>
                        <td>{{ $access->accessed_at?->toDayDateTimeString() }}</td>
                        <td>
                            @if ($access->was_successful)
                                <span class="badge">success</span>
                            @else
                                <span class="badge revoked">{{ $access->failure_reason ?? 'failed' }}</span>
                            @endif
                        </td>
                        <td>{{ $access->ip_address ?? 'Unknown' }}</td>
                        <td class="truncate">{{ $access->user_agent ?? 'Unknown' }}</td>
                        <td class="truncate">{{ $access->referrer ?? 'None' }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5" class="muted">No access attempts recorded for this link.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
        <div class="pagination">
            {{ $accesses->links() }}
        </div>
    </section>
@endsection
