<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Invoice {{ $invoice->invoice_number }}</title>
<style>
@page{size:A4 portrait;margin:14mm}*{box-sizing:border-box}body{margin:0;background:#eef1f4;color:#17202a;font:14px/1.45 Arial,sans-serif}.toolbar{max-width:210mm;margin:14px auto;display:flex;justify-content:space-between;align-items:center;gap:16px}.toolbar button{border:0;border-radius:7px;background:#111827;color:#fff;padding:11px 18px;font-weight:700;cursor:pointer}.sheet{width:210mm;min-height:297mm;margin:0 auto 24px;padding:18mm;background:#fff;box-shadow:0 8px 30px #0002}.top{display:flex;justify-content:space-between;gap:30px;padding-bottom:24px;border-bottom:3px solid var(--accent)}h1{margin:0;color:var(--accent);font-size:38px;letter-spacing:.04em}h2{margin:0 0 5px;font-size:19px}h3{margin:0 0 8px;color:var(--accent);font-size:12px;letter-spacing:.12em;text-transform:uppercase}p{margin:2px 0}.invoice-meta{text-align:right}.invoice-meta strong{display:block;font-size:17px}.parties{display:grid;grid-template-columns:1fr 1fr;gap:32px;margin:28px 0}.box{padding:16px;background:var(--soft);border-radius:8px}table{width:100%;border-collapse:collapse;margin-top:20px}th{color:#fff;background:var(--accent);text-align:left;padding:10px;font-size:11px;text-transform:uppercase;letter-spacing:.04em}td{padding:11px 10px;border-bottom:1px solid #d8dde3;vertical-align:top}.number{text-align:right;white-space:nowrap}.total{margin:22px 0 28px auto;width:45%;display:grid;grid-template-columns:1fr auto;gap:10px;padding:16px;background:var(--soft);font-size:17px}.total strong:last-child{color:var(--accent)}.payment{border-top:2px solid var(--accent);padding-top:18px;display:grid;grid-template-columns:1fr 1fr;gap:30px}.note{margin-top:28px;color:#56606b;font-size:12px}.classic{--accent:#243b64;--soft:#f0f4f9}.minimal{--accent:#202020;--soft:#f5f5f5}.minimal .top{border-bottom-width:1px}.minimal .box{padding-left:0;background:transparent}.minimal th{color:#222;background:#fff;border-top:1px solid #222;border-bottom:1px solid #222}.modern{--accent:#176b6b;--soft:#eaf5f3}.modern .sheet{border-top:11px solid var(--accent)}.modern h1{font-weight:300}@media print{body{background:#fff}.toolbar{display:none}.sheet{width:auto;min-height:auto;margin:0;padding:0;box-shadow:none}.modern .sheet{border-top:0}}
</style></head>
<body class="{{ $invoice->invoice_style }}"><div class="toolbar"><span>A4 portrait preview · {{ ucfirst($invoice->invoice_style) }} style</span><button onclick="window.print()">Print / Save as PDF</button></div><main class="sheet">
<header class="top"><div><h1>INVOICE</h1><p>Issued by an independent contractor</p></div><div class="invoice-meta"><span>Invoice number</span><strong>{{ $invoice->invoice_number }}</strong><span>Issue date</span><strong>{{ ($invoice->submitted_at ?? $invoice->created_at)->format('j F Y') }}</strong></div></header>
<section class="parties"><div class="box"><h3>From</h3><h2>{{ $invoice->crewProfile->legal_name }}</h2><p>{{ $invoice->crewProfile->address_line_1 }}</p>
@if ($invoice->crewProfile->address_line_2)<p>{{ $invoice->crewProfile->address_line_2 }}</p>@endif
<p>{{ $invoice->crewProfile->suburb }} {{ $invoice->crewProfile->state }} {{ $invoice->crewProfile->postcode }}</p><p>{{ $invoice->crewProfile->phone }}</p><p>ABN {{ $invoice->crewProfile->abn }}</p></div><div class="box"><h3>Bill to</h3><h2>DancePro Photography &amp; Video</h2><p>accounts@dancepro.com.au</p><p>ABN 77 221 718 867</p></div></section>
<table><thead><tr><th>Date</th><th>Description and time</th><th class="number">Quantity</th><th class="number">Unit price</th><th class="number">Total</th></tr></thead><tbody>
@foreach ($invoice->lines as $line)
<tr><td>{{ \Carbon\Carbon::parse($line->snapshot['date'])->format('D j M Y') }}</td><td><strong>{{ $line->snapshot['event'] }}</strong><br>{{ $line->snapshot['role'] }}
@if (data_get($line->snapshot, 'start') || data_get($line->snapshot, 'finish'))<br>{{ data_get($line->snapshot, 'start', '—') }}–{{ data_get($line->snapshot, 'finish', '—') }}@endif
@if ((float) $line->allowance_amount > 0)<br>Includes ${{ number_format((float) $line->allowance_amount, 2) }} allowances
@endif
</td><td class="number">{{ data_get($line->snapshot, 'hours') !== null ? number_format((float) data_get($line->snapshot, 'hours'), 2).' hrs' : '1' }}</td><td class="number">${{ number_format((float) data_get($line->snapshot, 'rate'), 2) }}</td><td class="number">${{ number_format((float) $line->line_total, 2) }}</td></tr>
@endforeach
</tbody></table>
<div class="total"><strong>Total due</strong><strong>${{ number_format((float)$invoice->total,2) }}</strong></div><section class="payment"><div><h3>Payment details</h3><p><strong>Account name:</strong> {{ $invoice->crewProfile->bank_account_name }}</p><p><strong>Bank:</strong> {{ $invoice->crewProfile->bank_name }}</p></div><div><h3>&nbsp;</h3><p><strong>BSB:</strong> {{ $invoice->crewProfile->bank_bsb }}</p><p><strong>Account number:</strong> {{ $invoice->crewProfile->bank_account_number }}</p></div></section><p class="note">Payment is due within 10 working days. Please use invoice number {{ $invoice->invoice_number }} as the payment reference.</p>
</main></body></html>
