@extends('layouts.admin', ['title' => 'Recognitions & rewards', 'heading' => 'Recognitions & rewards', 'subheading' => 'Celebrate great work with personal recognition badges.'])

@section('content')
@include('admin.crew-management._tabs')
<div class="recognition-grid">
<section class="card card-pad"><h2>Award recognition</h2><p class="muted">Choose a badge as a starting point, then personalise every detail before awarding it.</p>
<form method="POST" action="{{ route('admin.recognitions.store') }}">@csrf
<label>Start with a badge<select name="recognition_type_id" id="type-picker"><option value="">Create a one-off recognition</option>@foreach($types->where('is_active', true) as $type)<option value="{{ $type->id }}" data-title="{{ $type->name }}" data-icon="{{ $type->icon }}" data-design="{{ $type->design }}" data-message="{{ $type->default_message }}" @selected((string)old('recognition_type_id') === (string)$type->id)>{{ $type->icon }} {{ $type->name }}</option>@endforeach</select></label>
<div class="award-fields"><label>Title<input name="title" id="award-title" value="{{ old('title') }}" required maxlength="255"></label><label>Icon<input name="icon" id="award-icon" value="{{ old('icon') }}" required maxlength="20" placeholder="🌟"></label><label>Design<select name="design" id="award-design" required>@foreach($designs as $value => $label)<option value="{{ $value }}" @selected(old('design', 'dp-blue') === $value)>{{ $label }}</option>@endforeach</select></label></div>
<label>Personal message<textarea name="message" id="award-message" rows="4" required maxlength="2000">{{ old('message') }}</textarea></label>
<div class="award-fields"><label>Award date<input type="date" name="awarded_on" value="{{ old('awarded_on', now()->toDateString()) }}" required></label><label>Event (optional)<select name="scheduling_event_id"><option value="">Not connected to an event</option>@foreach($events as $event)<option value="{{ $event->id }}" @selected((string)old('scheduling_event_id') === (string)$event->id)>{{ $event->event_date?->format('d M Y') }} · {{ $event->name }}</option>@endforeach</select></label><label>Profile visibility<select name="show_on_profile"><option value="1" @selected(old('show_on_profile', '1') === '1')>Show on profile</option><option value="0" @selected(old('show_on_profile') === '0')>Keep private</option></select></label></div>
<fieldset class="crew-picker"><legend>Crew members</legend>@forelse($crewProfiles as $profile)<label><input type="checkbox" name="crew_profile_ids[]" value="{{ $profile->id }}" @checked(in_array($profile->id, old('crew_profile_ids', [])))><span><strong>{{ $profile->preferred_name ?: $profile->legal_name ?: $profile->user->name }}</strong><small>{{ $profile->user->email }}</small></span></label>@empty<p class="muted">Add crew members before awarding recognition.</p>@endforelse</fieldset>
<button type="submit" @disabled($crewProfiles->isEmpty())>Award recognition</button></form></section>
<section class="card card-pad preview-card"><h2>Badge preview</h2><div class="recognition-preview"><span class="recognition-roundel"><img src="{{ asset('images/brand/dancepro-icon-blue.png') }}" alt=""><span id="preview-centre" class="recognition-centre design-dp-blue">🌟</span></span><strong id="preview-title">Recognition title</strong><span id="preview-message">Your personal message will appear here.</span></div></section>
</div>
<section class="card card-pad"><h2>Recognition badge bank</h2><p class="muted">Reusable starting points. Editing a badge never changes recognitions already awarded.</p>
<details><summary class="button secondary">Add recognition type</summary><form class="type-row" method="POST" action="{{ route('admin.recognition-types.store') }}">@csrf <label>Title<input name="name" required></label><label>Icon<input name="icon" required maxlength="20"></label><label>Design<select name="design">@foreach($designs as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label>Default message<textarea name="default_message"></textarea></label><input type="hidden" name="is_active" value="1"><button>Add badge</button></form></details>
@foreach($types as $type)<form class="type-row" method="POST" action="{{ route('admin.recognition-types.update', $type) }}">@csrf @method('PUT') <label>Title<input name="name" value="{{ $type->name }}" required></label><label>Icon<input name="icon" value="{{ $type->icon }}" required maxlength="20"></label><label>Design<select name="design">@foreach($designs as $value => $label)<option value="{{ $value }}" @selected($type->design === $value)>{{ $label }}</option>@endforeach</select></label><label>Default message<textarea name="default_message">{{ $type->default_message }}</textarea></label><label>Status<select name="is_active"><option value="1" @selected($type->is_active)>Active</option><option value="0" @selected(!$type->is_active)>Inactive</option></select></label><button>Save</button></form>@endforeach</section>
<section class="card"><div class="card-pad"><h2>Recognition history</h2><p class="muted">Awards remain here permanently with their original personalised details.</p></div><table><thead><tr><th>Badge</th><th>Crew member</th><th>Awarded</th><th>Event</th><th>Profile</th></tr></thead><tbody>@forelse($recognitions as $recognition)<tr><td><strong>{{ $recognition->icon }} {{ $recognition->title }}</strong><div class="muted">{{ $recognition->message }}</div></td><td>{{ $recognition->crewProfile->preferred_name ?: $recognition->crewProfile->user->name }}</td><td>{{ $recognition->awarded_on->format('d M Y') }}<div class="muted">by {{ $recognition->awardedBy?->name ?: 'DancePro' }}</div></td><td>{{ $recognition->schedulingEvent?->name ?: '—' }}</td><td>{{ $recognition->show_on_profile ? 'Visible' : 'Private' }}</td></tr>@empty<tr><td colspan="5" class="muted">No recognition has been awarded yet.</td></tr>@endforelse</tbody></table></section>
<section class="card card-pad"><h2>Rewards</h2><p class="muted">Rewards are not active yet. Recognition badges have no monetary value and cannot be redeemed.</p></section>
@endsection
@push('styles')<style>
.recognition-grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(240px,1fr);gap:16px;margin-bottom:16px}.award-fields{display:grid;grid-template-columns:1fr 100px 1fr;gap:10px}.crew-picker{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:8px;margin:15px 0;padding:12px;border:1px solid var(--line);border-radius:6px}.crew-picker label{display:flex;align-items:center;gap:8px}.crew-picker input{width:18px;min-height:18px}.crew-picker small{display:block;color:var(--muted)}.preview-card{text-align:center}.recognition-preview{display:flex;flex-direction:column;align-items:center;gap:8px;padding:24px 8px}.recognition-roundel{position:relative;width:110px;height:110px}.recognition-roundel img{width:100%}.recognition-centre{position:absolute;inset:26px;display:grid;place-items:center;border:2px solid #fff;border-radius:50%;color:#fff;font-size:29px}.design-dp-blue{background:#087ca6}.design-gold-star{background:#f3b51b}.design-purple-heart{background:#804bc7}.design-teal-compass{background:#159c9c}.design-red-bolt{background:#d94343}.design-green-shield{background:#249b68}.design-midnight-crown{background:#082b38}.design-rainbow{background:conic-gradient(#ef5350,#ffca28,#45b86b,#23a9d5,#7857c8,#ef5350)}details{margin:12px 0}.type-row{display:grid;grid-template-columns:minmax(150px,1fr) 75px minmax(140px,1fr) minmax(220px,2fr) 110px auto;align-items:end;gap:9px;padding:13px 0;border-top:1px solid var(--line)}.type-row textarea{min-height:44px}@media(max-width:1000px){.recognition-grid{grid-template-columns:1fr}.type-row{grid-template-columns:1fr 90px 1fr}}@media(max-width:620px){.award-fields,.type-row{grid-template-columns:1fr}}
</style>@endpush
@push('scripts')<script nonce="{{ request()->attributes->get('csp_nonce') }}">
const picker=document.getElementById('type-picker'),fields={title:document.getElementById('award-title'),icon:document.getElementById('award-icon'),design:document.getElementById('award-design'),message:document.getElementById('award-message')};const preview=()=>{document.getElementById('preview-title').textContent=fields.title.value||'Recognition title';document.getElementById('preview-message').textContent=fields.message.value||'Your personal message will appear here.';const centre=document.getElementById('preview-centre');centre.textContent=fields.icon.value||'🌟';centre.className=`recognition-centre design-${fields.design.value}`};picker?.addEventListener('change',()=>{const option=picker.selectedOptions[0];if(!option?.value)return;Object.keys(fields).forEach(key=>fields[key].value=option.dataset[key]||'');preview()});Object.values(fields).forEach(field=>field?.addEventListener('input',preview));preview();
</script>@endpush
