@extends('layouts.public', ['title' => 'Book DancePro for your concert'])
@section('content')
<section class="hero"><div class="container"><div class="eyebrow">Concert booking request</div><h1>Tell us about your events.</h1><p class="lead">Add every concert and dress rehearsal that needs DancePro coverage. You can add as many performance rows as required.</p></div></section>
<section class="section"><div class="container" style="max-width:900px">@if($errors->any())<div class="error"><strong>Please check the form.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('concert-bookings.store') }}">@csrf
    <div style="position:absolute;left:-10000px;width:1px;height:1px;overflow:hidden" aria-hidden="true">
        <label for="website">Website</label>
        <input id="website" name="website" type="text" value="" tabindex="-1" autocomplete="off">
    </div>
<div class="card card-body"><h2>Studio details</h2><div class="grid" style="grid-template-columns:repeat(2,1fr)"><label>Studio/company name<input name="studio_name" value="{{ old('studio_name') }}" required></label><label>Owner/director name<input name="contact_name" value="{{ old('contact_name') }}" required></label><label>Email<input type="email" name="contact_email" value="{{ old('contact_email') }}" required></label><label>Phone number<input name="contact_phone" value="{{ old('contact_phone') }}" required></label></div></div>
<div class="card card-body" style="margin-top:20px"><h2>Services</h2><label>Would you like dress rehearsal portrait photography?<select id="portrait-photography-interest" name="portrait_photography_interest" required><option value="yes" @selected(old('portrait_photography_interest') === 'yes')>Yes please</option><option value="no" @selected(old('portrait_photography_interest', 'no') === 'no')>No thanks</option><option value="unsure" @selected(old('portrait_photography_interest') === 'unsure')>Unsure, please send me more information</option></select></label><label class="choice"><input type="hidden" name="wants_concert_photography" value="0"><input id="concert-photography" type="checkbox" name="wants_concert_photography" value="1" @checked(old('wants_concert_photography', true))><span>Concert photography</span></label><label class="choice"><input type="hidden" name="wants_concert_videography" value="0"><input id="concert-videography" type="checkbox" name="wants_concert_videography" value="1" @checked(old('wants_concert_videography'))><span>Concert videography</span></label></div>
<div class="card card-body" style="margin-top:20px"><h2>Event details</h2><p class="muted">Use one row for each concert or DR portrait session. Select Other venue if the location is not listed.</p><div id="booking-items">@php($defaultEventType = $eventTypes->firstWhere('uuid', $selectedEventTypeUuid) ?? $eventTypes->firstWhere('code', 'concert') ?? $eventTypes->first())@php($rows = old('items', [['item_type' => 'concert', 'event_type_definition_id' => $defaultEventType?->id]]))@foreach($rows as $index => $row)@include('public.concert-bookings._event-row', compact('index', 'row', 'venues', 'eventTypes'))@endforeach</div><template id="booking-item-template">@include('public.concert-bookings._event-row', ['index' => '__INDEX__', 'row' => ['item_type' => 'concert', 'event_type_definition_id' => $defaultEventType?->id], 'venues' => $venues, 'eventTypes' => $eventTypes])</template><button class="button secondary" type="button" id="add-booking-item" style="margin-top:18px">Add another event</button></div>
<div id="video-delivery" class="card card-body" style="margin-top:20px" @if(!old('wants_concert_videography')) hidden @endif><h2>Video delivery</h2><label>Approximate number of performing families<input type="number" name="approximate_family_count" value="{{ old('approximate_family_count') }}" min="1"></label><label>Postal address<textarea name="postal_address" style="min-height:90px;width:100%">{{ old('postal_address') }}</textarea></label><label>What worked, or did not work, in previous concert videos?<textarea name="previous_video_feedback" style="min-height:120px;width:100%">{{ old('previous_video_feedback') }}</textarea></label></div>
<div class="card card-body" style="margin-top:20px"><h2>Booking requirements</h2><p class="muted">Please read and confirm the requirements that apply to the services you selected.</p>
<div><h3>General booking confirmation</h3><label class="choice"><input type="checkbox" name="accepted_requirements[]" value="accurate" required @checked(in_array('accurate', old('accepted_requirements', [])))><span>The information provided is accurate and changes will be sent to DancePro promptly.</span></label></div>
<div id="portrait-requirements" class="agreement-group" @if(old('portrait_photography_interest', 'no') !== 'yes') hidden @endif><h3>Dress rehearsal portrait photography</h3>@foreach(['portrait_space' => 'Portrait sessions will have a powered 12 × 10 metre space and dancers will be brought out in costume.', 'no_personal_backdrop_photos' => 'Parents and dancers will not take personal photos on the portrait backdrop.'] as $value => $label)<label class="choice"><input type="checkbox" name="accepted_requirements[]" value="{{ $value }}" @checked(in_array($value, old('accepted_requirements', [])))><span>{{ $label }}</span></label>@endforeach</div>
<div id="photography-requirements" class="agreement-group" @if(!old('wants_concert_photography', true)) hidden @endif><h3>Concert photography</h3>@foreach(['minimum_spend' => 'I understand the concert photography minimum-spend requirements.', 'photographer_seat' => 'A suitable auditorium position or seat will be arranged for the photographer.', 'no_audience_recording' => 'Audience members will be told that personal filming and photography are not permitted.', 'promote_gallery' => 'DancePro service information and the unique gallery login will be shared with families and printed in the programme.', 'credit_images' => 'Published or printed DancePro images will credit or link to DancePro.'] as $value => $label)<label class="choice"><input type="checkbox" name="accepted_requirements[]" value="{{ $value }}" @checked(in_array($value, old('accepted_requirements', [])))><span>{{ $label }}</span></label>@endforeach</div>
<div id="videography-requirements" class="agreement-group" @if(!old('wants_concert_videography')) hidden @endif><h3>Concert videography</h3>@foreach(['video_access' => 'Videography bookings will provide theatre access 1.5–2 hours before the concert.', 'video_space_audio' => 'Videography bookings will provide 5–6 adjacent seats, an unobstructed view, and an arranged XLR sound feed.', 'programme_invoice' => 'The current programme will be supplied and the invoice finalised before video release.'] as $value => $label)<label class="choice"><input type="checkbox" name="accepted_requirements[]" value="{{ $value }}" @checked(in_array($value, old('accepted_requirements', [])))><span>{{ $label }}</span></label>@endforeach</div>
</div>
<button class="button" type="submit" style="margin-top:20px">Submit booking request</button></form></div></section>
@endsection
@push('scripts')<script nonce="{{ request()->attributes->get('csp_nonce') }}">
function configureVenueRow(row){const select=row.querySelector('.venue-select');const fields=row.querySelector('.other-venue-fields');const address=row.querySelector('.selected-venue-address');const inputs=fields.querySelectorAll('input');const update=()=>{const other=select.value==='other';fields.hidden=!other;inputs.forEach(input=>input.required=other);address.textContent=!other&&select.selectedOptions[0]?.dataset.address?select.selectedOptions[0].dataset.address:'';};select.addEventListener('change',update);update();}
document.querySelectorAll('.booking-item').forEach(configureVenueRow);
document.getElementById('add-booking-item').addEventListener('click',()=>{const box=document.getElementById('booking-items');const index=box.querySelectorAll('.booking-item').length;box.insertAdjacentHTML('beforeend',document.getElementById('booking-item-template').innerHTML.replaceAll('__INDEX__',index));configureVenueRow(box.lastElementChild);});
const portraitInterest=document.getElementById('portrait-photography-interest');const photography=document.getElementById('concert-photography');const videography=document.getElementById('concert-videography');
function toggleSection(section,visible){section.hidden=!visible;section.querySelectorAll('input[type="checkbox"]').forEach(input=>{input.required=visible;if(!visible)input.checked=false;});}
function updateConditionalSections(){toggleSection(document.getElementById('portrait-requirements'),portraitInterest.value==='yes');toggleSection(document.getElementById('photography-requirements'),photography.checked);toggleSection(document.getElementById('videography-requirements'),videography.checked);const videoDelivery=document.getElementById('video-delivery');videoDelivery.hidden=!videography.checked;videoDelivery.querySelectorAll('input,textarea').forEach(field=>{field.disabled=!videography.checked;field.required=videography.checked;});}
function updateFirstEventForPortrait(){const firstEventType=document.querySelector('.event-type-select');if(!firstEventType)return;if(portraitInterest.value==='yes'){firstEventType.value='dress_rehearsal';firstEventType.dataset.autoDrPortrait='true';}else if(firstEventType.dataset.autoDrPortrait==='true'){firstEventType.value='concert';delete firstEventType.dataset.autoDrPortrait;}}
document.addEventListener('change',event=>{if(event.target.matches('.event-type-select'))delete event.target.dataset.autoDrPortrait;});
portraitInterest.addEventListener('change',()=>{updateFirstEventForPortrait();updateConditionalSections();});
[photography,videography].forEach(control=>control.addEventListener('change',updateConditionalSections));updateConditionalSections();
</script>@endpush
